# Site
name: 'Anton o herbacie'
description: ''
logo: ''
favicon: 'assets/images/other/ua.jpg'
baseurl: '/'
disqus: 'demowebsite'
email: 'antonoherbacie@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
staticman_url: https://antonoherbacie-comments.herokuapp.com/v2/entry/Septiconn/septiconn.github.io/main/comments

# Google Analytics
google_analytics: G-M21W0DLNQ4

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-responsive-image
  
authors:
    anton:
      name:           Anton
      site:           
      avatar:         
      bio:            
      email:          antonoherbacie@gmail.com
      twitter:
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Anton
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false
reCaptcha:
    siteKey: 6Lc6TaIeAAAAAI6VigKRXSlBbQhOMRrEYGCCGtx3
    secret: BTtz6pmGSNPiKe9CBOLTQO7qc3aPXcfKQ2ZpIGvr1JI2tIlt+dEjbnVlyRBOVavxRGfEpeTlLDsSoq9tvPXfRj+8Py/TijR1QtYlvXE9ey08kQZ8oH/D5e0w9Ag/VJYJHbwgbR3oP6ewwrDxFBnP95Hvyhjyf/T2tVoD1VQyOusIjPJW5+bnlP/u5f/PMZMe4kNCn0Ix2T6RW9MlxvSlPBJotF58qG9aoIgc2x9XwbqsS6gDJVc3XApTX4Y2gYnpZFHoOMKMLnEER6YZjGcNX6f6JjIzXeT23aLNm3kQVatKGVPCWdAbjZP8oBH898akt/cHLqz8Q/oSbhp7/Wec/oxbuBTwpdxLIq6t5KwLok4LSEY5X1uQnZv/TIKCo3BR4ODiMqBnnHKO/Aqy63yyDt5Q2MM8e2RpBzQBUawKnA8XR99QyFRTjlNfjrZ7POU9f3yBt4Laug7Q7WZxUkhVoX9SP0LKGGl5vuD5M4DcTR9Iy1xjDJIljFxB8ngQAFoD6U1OESCOL21zbP+OAhJ0S+vBAh7niT/YfxJ6w/3K9qJthAPgw00gDU/WOYY+Yih2xfy7dX3Z7aKpaL6ImWMFhZCNxTBe0wcrLTdDU2TZqNHyfN4OFFMr96mQQxAgH3OxfS+/snbVEqz1TU7OcmL9BKcuLWUULLNyZaWPy7BCVUs=