# Site
name: 'Anton o herbacie'
description: ''
logo: ''
favicon: 'assets/images/ua.jpg'
baseurl: '/'
disqus: 'demowebsite'
email: 'antonoherbacie@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
staticman_url: https://antonoherbacie-comments.herokuapp.com/v2/entry/Septiconn/septiconn.github.io/main/comments

# Google Analytics
google_analytics: G-M21W0DLNQ4

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Anton
      site:           
      avatar:         
      bio:            
      email:          antonoherbacie@gmail.com
      twitter:        

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Anton
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]


reCaptcha:
    siteKey: 6Lc6TaIeAAAAAI6VigKRXSlBbQhOMRrEYGCCGtx3
    secret: BTtz6pmGSNPiKe9CBOLTQO7qc3aPXcfKQ2ZpIGvr1JI2tIlt+dEjbnVlyRBOVavxRGfEpeTlLDsSoq9tvPXfRj+8Py/TijR1QtYlvXE9ey08kQZ8oH/D5e0w9Ag/VJYJHbwgbR3oP6ewwrDxFBnP95Hvyhjyf/T2tVoD1VQyOusIjPJW5+bnlP/u5f/PMZMe4kNCn0Ix2T6RW9MlxvSlPBJotF58qG9aoIgc2x9XwbqsS6gDJVc3XApTX4Y2gYnpZFHoOMKMLnEER6YZjGcNX6f6JjIzXeT23aLNm3kQVatKGVPCWdAbjZP8oBH898akt/cHLqz8Q/oSbhp7/Wec/oxbuBTwpdxLIq6t5KwLok4LSEY5X1uQnZv/TIKCo3BR4ODiMqBnnHKO/Aqy63yyDt5Q2MM8e2RpBzQBUawKnA8XR99QyFRTjlNfjrZ7POU9f3yBt4Laug7Q7WZxUkhVoX9SP0LKGGl5vuD5M4DcTR9Iy1xjDJIljFxB8ngQAFoD6U1OESCOL21zbP+OAhJ0S+vBAh7niT/YfxJ6w/3K9qJthAPgw00gDU/WOYY+Yih2xfy7dX3Z7aKpaL6ImWMFhZCNxTBe0wcrLTdDU2TZqNHyfN4OFFMr96mQQxAgH3OxfS+/snbVEqz1TU7OcmL9BKcuLWUULLNyZaWPy7BCVUs=